sudo: required
dist: trusty
language: c
env:
    matrix:
        - OS_TYPE=fedora
        - OS_TYPE=centos

services:
    - docker

before_install:
    - docker pull $OS_TYPE

script:
    - >
        docker run --privileged --rm=true --tty=true
        -v `pwd`:/libstoragemgmt-code:rw $OS_TYPE
        /bin/bash -c /libstoragemgmt-code/test/docker_travis_test.sh
